In [1]:
import pandas as pd
import numpy as np
import geopandas as gpd

In [2]:
gdf_delitos = gpd.read_file("../output/tweets-delitos-localizados.geojson")

In [3]:
df = gdf_delitos.drop(columns=['geometry', 'Unnamed: 0', "index_right", "stroke", "stroke-width", "stroke-opacity", "fill", "fill-opacity", "Description"])  # Elimina la columna de geometría

In [4]:
df.head()

,DisplayName,UserName,Timestamp,Content,Comments,Likes,Retweets,Interactions,Delito,Coordenadas,latitude,longitude,Name,Zona
0,Segura EP,@segura_ep,2023-09-01 03:20:23+00:00,Desde las cámaras de videovigilancia observamo...,0.0,2.0,8.0,2314.0,1,"-2.1384511, -79.8913772",-2.138451,-79.891377,Sauces,Norte
1,Segura EP,@segura_ep,2023-08-24 22:08:45+00:00,#Alerta | Desde las cámaras de videovigilancia...,0.0,3.0,7.0,840.0,1,"-2.1269033, -79.9000788",-2.126903,-79.900079,Sauces,Norte
2,Segura EP,@segura_ep,2023-08-22 05:37:57+00:00,Cámaras de videovigilancia monitorean el accid...,0.0,3.0,17.0,2266.0,1,"-2.1329058, -79.8899186",-2.132906,-79.889919,Sauces,Norte
3,Segura EP,@segura_ep,2023-07-30 06:50:26+00:00,#Alerta | Desde las cámaras de videovigilancia...,0.0,2.0,18.0,1490.0,1,"-2.1413962, -79.8887857",-2.141396,-79.888786,Sauces,Norte
4,Segura EP,@segura_ep,2023-07-22 00:29:11+00:00,Cámaras de videovigilancia captan el accidente...,0.0,1.0,1.0,1240.0,1,"-2.1329058, -79.8899186",-2.132906,-79.889919,Sauces,Norte

In [5]:
df["Date"] = df["Timestamp"].dt.date

In [6]:
df["Time"] = df["Timestamp"].dt.time

In [7]:
df.drop(columns="Timestamp", inplace=True)

In [8]:
df

,DisplayName,UserName,Content,Comments,Likes,Retweets,Interactions,Delito,Coordenadas,latitude,longitude,Name,Zona,Date,Time
0,Segura EP,@segura_ep,Desde las cámaras de videovigilancia observamo...,0.0,2.0,8.0,2314.0,1,"-2.1384511, -79.8913772",-2.138451,-79.891377,Sauces,Norte,2023-09-01,03:20:23
1,Segura EP,@segura_ep,#Alerta | Desde las cámaras de videovigilancia...,0.0,3.0,7.0,840.0,1,"-2.1269033, -79.9000788",-2.126903,-79.900079,Sauces,Norte,2023-08-24,22:08:45
2,Segura EP,@segura_ep,Cámaras de videovigilancia monitorean el accid...,0.0,3.0,17.0,2266.0,1,"-2.1329058, -79.8899186",-2.132906,-79.889919,Sauces,Norte,2023-08-22,05:37:57
3,Segura EP,@segura_ep,#Alerta | Desde las cámaras de videovigilancia...,0.0,2.0,18.0,1490.0,1,"-2.1413962, -79.8887857",-2.141396,-79.888786,Sauces,Norte,2023-07-30,06:50:26
4,Segura EP,@segura_ep,Cámaras de videovigilancia captan el accidente...,0.0,1.0,1.0,1240.0,1,"-2.1329058, -79.8899186",-2.132906,-79.889919,Sauces,Norte,2023-07-22,00:29:11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
602,NaN,NaN,"En el sector de la Huancavilca Sur , delincuen...",0.0,0.0,0.0,0.0,1,"-2.2349311, -79.9002713",-2.234931,-79.900271,Huancavilca Sur,Sur,2022-04-16,15:40:46
603,NaN,NaN,Solo en Guayaquil: Delincuente fingió conocer ...,0.0,0.0,0.0,0.0,1,"-2.2338739, -79.90368699999999",-2.233874,-79.903687,Huancavilca Sur,Sur,2023-05-04,11:00:00
604,NaN,NaN,#Guayaquil #Delincuencia Intento de Robo se re...,0.0,0.0,0.0,0.0,1,"-2.0646512, -79.8926809",-2.064651,-79.892681,Mucho Lote 2,Norte,2021-11-29,13:25:00
605,NaN,NaN,Roban a un estudiante en el cerro Santa Ana,0.0,0.0,0.0,0.0,1,"-2.1821129, -79.8755336",-2.182113,-79.875534,Las Peñas,Centro,2022-03-14,19:23:46
606,NaN,NaN,"Después de una persecución, un grupo de delinc...",0.0,0.0,0.0,0.0,1,"-2.1534532, -79.887782",-2.153453,-79.887782,Ciudadela Simon Bolivar,Norte,2023-04-29,11:12:00

In [9]:
df.drop_duplicates(subset=['Content'], inplace=True)

In [10]:
df.reset_index(drop= True, inplace = True)

In [11]:
keyword_dict = {
    'Robo': ['robo', 'hurto', 'atraco', 'saqueo', 'apropiacion indebida','asalt','roba'],
    'Agresión': ['agresion', 'pelea', 'violencia', 'golpiza', 'ataque', 'maltrato','balacera','hirio','heri','golp','bala','puñetes', 'dispar', 'paliza', 'balead','gresion' ],
    'Drogas': ['drogas', 'narcotrafico', 'estupefacientes', 'consumo', 'venta'],
    'Homicidio': ['homicidio', 'muert', 'asesin', 'sicariato','masacre','desmembr', 'decapit', 'acribill', 'descuarti', 'femicidio', 'mata', 'mato', ],
    'Accidente Vehicular': ['atropella','accidente', 'colision', 'choque', 'atropello', 'vehiculo', 'conductor','siniestro de transito','volco','volcamiento','volcado'],
    'Secuestro': ['secuestr', 'retenido', 'plagio', 'liberacion', 'rescate', 'encerr'],
    'Fraude': ['fraude', 'estafa', 'engaño', 'falsificacion', 'delito financiero', 'extorsionadores'],
    'Extorsión':['vacuna', 'extorsion'],
    'Incendio': ['incendio', 'fuego', 'quemar', 'combustion', 'siniestro'],
    'Vandalismo': ['vandalismo', 'destrozo', 'daños', 'destruccion', 'pintadas','explosivo','bomba','relaciones sexuales', 'dinamita'],
    'Violación': ['violacion', 'agresion sexual', 'abuso sexual', 'abusar', 'violador'],
    # Agrega más tipos de delitos y palabras clave según sea necesario
}

In [12]:
def remove_tildes(texto):
    tildes_dict = {
        'á': 'a',
        'é': 'e',
        'í': 'i',
        'ó': 'o',
        'ú': 'u',
        'Á': 'A',
        'É': 'E',
        'Í': 'I',
        'Ó': 'O',
        'Ú': 'U',
    }

    texto_sin_tildes = ''.join(tildes_dict.get(caracter, caracter) for caracter in texto)
    return texto_sin_tildes

def categorizar_delito(tweet):
    contenido = remove_tildes(tweet['Content'].lower())
    
    # Buscar palabras clave en el contenido del tweet
    for delito, palabras_clave in keyword_dict.items():
        for palabra in palabras_clave:
            if palabra in contenido:
                return delito
    
    # Si no se encuentra ninguna coincidencia, asignar 'Otro'
    return 'Otro'

In [13]:
df['TipoDelito'] = df.apply(categorizar_delito, axis=1)

In [14]:
df.loc[df["TipoDelito"]=="Otro",:].shape

(37, 16)

In [15]:
def cambiar_Tipo_Delito(indices, tipo_delito):
    for indice in indices:
        df.at[(indice-2),'TipoDelito'] = tipo_delito

In [16]:
cambiar_Tipo_Delito([47,144,516], 'Robo')
cambiar_Tipo_Delito([305,352,462], 'Homicidio')
cambiar_Tipo_Delito([189,265,563,564,565], 'Vandalismo')
cambiar_Tipo_Delito([526], 'Extorsión')

In [17]:
df = df.loc[df["TipoDelito"]!="Otro",:]

In [18]:
df_interactions = df.dropna(subset="DisplayName")

In [19]:
df.to_csv("../output/tweets_con_tipo_delito.csv", index=False)

In [20]:
interXdelito = df_interactions.groupby("TipoDelito")["Comments", "Likes", "Retweets", "Interactions"].mean().reset_index()

C:\Users\lo206\AppData\Local\Temp\ipykernel_19480\1523327142.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  interXdelito = df_interactions.groupby("TipoDelito")["Comments", "Likes", "Retweets", "Interactions"].mean().reset_index()

In [21]:
interXdelito

            TipoDelito    Comments       Likes    Retweets   Interactions
0  Accidente Vehicular    6.733945   30.211009  100.990826  141625.238532
1             Agresión   31.813953  158.697674  511.627907  405122.372093
2            Extorsión  251.000000   29.178000  950.500000  693000.000000
3               Fraude    9.500000   90.000000  166.000000  179777.500000
4            Homicidio   14.057692  112.403846  310.634615  645870.692308
5             Incendio    0.500000    8.400000   30.300000  229952.700000
6                 Robo   43.704545  173.727303  594.954545  592946.575758
7            Secuestro    0.000000   60.000000  176.000000  134000.000000
8           Vandalismo   44.250000  108.250000  339.625000  526665.375000

In [22]:
interXdelito.to_csv("../output/intercciones-por-delito-mean.csv", index=False)

In [29]:
barrioXdelito = pd.pivot_table(df, values = 'Likes', columns=['Zona'], index=['TipoDelito'], aggfunc="count").reset_index()

In [30]:
barrioXdelito

Zona           TipoDelito  Centro  Norte   Sur
0     Accidente Vehicular    17.0   50.0  45.0
1                Agresión     2.0   38.0  37.0
2                  Drogas     1.0    NaN   NaN
3               Extorsión     1.0    3.0   2.0
4                  Fraude     NaN    3.0   1.0
5               Homicidio     2.0   59.0  32.0
6                Incendio     1.0    7.0   3.0
7                    Robo    29.0  100.0  97.0
8               Secuestro     NaN    1.0   3.0
9              Vandalismo     2.0    9.0   5.0

In [31]:
barrioXdelito = barrioXdelito.fillna(0)

In [32]:
barrioXdelito.to_csv("../output/delito-por-zona.csv", index=False)